import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { ToastContainer } from "react-toastify";

import StoreProvider from "./StoreProvider";
import QueryClientProvider from "./QueryClientProvider";

import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Food Ordering App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <QueryClientProvider>
          <StoreProvider>
            {children}
            <ToastContainer autoClose={3000} />
          </StoreProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
